name: meman
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Utils
  hive: ^2.2.3
  shared_preferences: 2.0.13
  connectivity_plus: 2.2.1
  intl: 0.17.0
  google_fonts: ^3.0.1
  country_code_picker: ^3.0.0
  otp_text_field: ^1.1.1
  flutter_font_icons: ^2.2.5
  permission_handler: 10.2.0
  chopper: 4.0.1
  freezed_annotation: 0.14.2
  dartz: ^0.10.0
  equatable: ^2.0.3
  logging: ^1.0.2

  # State Management
  get: ^4.6.5
  flutter_hooks: ^0.18.3
  hooks_riverpod: 1.0.3

  # Firebase
  firebase_core: 1.20.0
  firebase_auth: 3.3.13
  firebase_messaging: 11.2.8
  cloud_firestore: 3.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  chopper_generator: ^4.0.1
  flutter_gen_runner:
  freezed: 0.14.5
  json_serializable: ^5.0.2
  firebase_core_platform_interface: 4.5.1
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/colored_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf